runtime: go111

handlers:
  
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  
- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt
  
- url: /apple-touch-icon\.png
  static_files: static/apple-touch-icon.png
  upload: static/apple-touch-icon\.png
  
- url: /js
  static_dir: static/js
  
- url: /img
  static_dir: static/img
  
- url: /.*
  script: auto